config/routes.rb
Rails.application.routes.draw do
  root 'couriers#index'

  resources :couriers do
    resources :packages, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :courier_packages
  has_many :packages, through: :courier_packages

  validates :name, :email, presence: true

  COURIERS_PER_PAGE = 5
end

app/models/courier_package.rb
class CourierPackage < ApplicationRecord
  belongs_to :courier
  belongs_to :package
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :courier_packages
  has_many :couriers, through: :courier_packages

  validates :tracking_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  include Pagy::Backend

  def index
    sorted_couriers = Courier.all.order(:name)

    @pagy, @couriers = pagy(sorted_couriers, items: Courier::COURIERS_PER_PAGE)
  end

  def show
    @courier = Courier.find_by(id: params[:id])

    @package = @courier.packages.new
  end

  def new
    @courier = Courier.new
  end

  def edit
    @courier = Courier.find_by(id: params[:id])
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier, notice: t('courier_cr')
    else
      flash[:alert] = t('courier_cr_err')

      render :new
    end
  end

  def update
    @courier = Courier.find_by(id: params[:id])

    if @courier.update(courier_params)
      redirect_to @courier, notice: t('courier_upd')
    else
      flash[:alert] = t('courier_upd_err')

      render :edit
    end
  end

  private

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def create
    courier = Courier.find_by(id: params[:courier_id])

    package = courier.packages.create(package_params)

    if package.save
      redirect_to courier, notice: t('package_cr',
                                     tracking_number: package.tracking_number,
                                     courier: courier.name)
    else
      redirect_to courier, alert: t('package_cr_err')
    end
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def show_errors(object, field)
    object.errors.messages[field].join(', ') if object && object.errors[field]
  end

  def error_class(object, field)
    return unless object

    'has-error' if object.errors.include?(field)
  end
end

app/views/couriers/_courier_list.html.haml
%tr
  %td
    %span.in-grey-900.font-16.fw-300= courier_list.name
  %td
    = link_to t('show'), courier_path(courier_list.id), class: "general-order-number"
    = link_to t('edit'), edit_courier_path(courier_list.id), class: "general-order-number"

app/views/couriers/_courier_list_xs.html.haml
.general-cart-item.divider-lg-bottom.pt-0
  %table.table
    %tr
      %td.col-half
        %span.in-grey-600= t('name')
      %td.col-half
        %span.in-grey-900.font-16.fw-300= courier_list_xs.name
    %tr
      %td
        %span.in-grey-600= t('settings')
      %td
        = link_to t('show'), courier_path(courier_list_xs.id), class: "general-order-number"
        = link_to t('edit'), edit_courier_path(courier_list_xs.id), class: "general-order-number"

app/views/couriers/_form_courier.html.haml
%p.in-gold-500.font-18.mb-25
= form_for @courier, url: couriers_path, method: :post, class: "general-form-md" do |f|
  .form-group.mb-35{class: "#{error_class(@courier, :name)}"}
    = f.label :name, t('name'), class: "control-label input-label"
    = f.text_field :name, placeholder: t('enter_name'), class: "form-control"
    %span.help-block= show_errors(@courier, :name)
  .form-group.mb-35{class: "#{error_class(@courier, :email)}"}
    = f.label :email, t('email'),class: "control-label input-label"
    = f.email_field :email, placeholder: t('enter_email'), class: "form-control"
    %span.help-block= show_errors(@courier, :email)
  .general-text-align
    = f.button t('create'), class: 'btn btn-default mb-35', name: "commit", value: "create"

app/views/couriers/_form_courier_edit.html.haml
%p.in-gold-500.font-18.mb-25
= form_for @courier, url: courier_path, method: :patch, class: "general-form-md" do |f|
  .form-group.mb-35{class: "#{error_class(@courier, :name)}"}
    = f.label :name, t('name'), class: "control-label input-label"
    = f.text_field :name, placeholder: t('enter_name'), class: "form-control"
    %span.help-block= show_errors(@courier, :name)
  .form-group.mb-35{class: "#{error_class(@courier, :email)}"}
    = f.label :email, t('email'),class: "control-label input-label"
    = f.email_field :email, placeholder: t('enter_email'), class: "form-control"
    %span.help-block= show_errors(@courier, :email)
  .general-text-align
    = f.button t('save'), class: 'btn btn-default mb-35', name: "commit", value: "update"

app/views/couriers/_form_package.html.haml
%p.in-gold-500.font-18.mb-25
  = t('new_package')
= form_for @package, url: courier_packages_path(@courier.id), method: :post, class: "general-form-md" do |f|
  .form-group.mb-35{class: "#{error_class(@package, :tracking_number)}"}
    = f.label :tracking_number, t('tracking_number'), class: "control-label input-label"
    = f.text_field :tracking_number, placeholder: t('enter_tracking_number'), class: "form-control"
    %span.help-block= show_errors(@package, :tracking_number)
  .form-group.mb-35{class: "#{error_class(@package, :delivery_status)}"}
    = f.label :delivery_status, t('delivery_status'),class: "control-label input-label"
    = f.check_box :delivery_status, class: "form-control"
    %span.help-block= show_errors(@package, :delivery_status)
  .general-text-align
    = f.button t('create'), class: 'btn btn-default mb-35', name: "commit", value: "create"

app/views/couriers/edit.html.haml
%main.container
  %h1.general-title-margin
    = t('edit_courier')
    .row.mb-60
      .col-sm-5
        = render partial: 'form_courier_edit'

app/views/couriers/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25= t('couriers')
  = link_to 'New courier', new_courier_path, class: "btn btn-primary"
  .visible-xs
    - if !Courier.exists?
      .jumbotron.text-center.mb-0
        %p= t('no_couriers')
    - else
      = render partial: 'courier_list_xs', collection: @couriers
      - if @pagy.pages > 1
        .text-center
          = render partial: 'pagy/nav', locals: { pagy: @pagy }
  .hidden-xs.mb-res-50
    - if !Courier.exists?
      .jumbotron.text-center.mb-0
        %p= t('no_couriers')
    - else
      %table.table.table-hover
        %thead
          %tr
            %th
              %span.in-grey-600= t('name')
            %th
              %span.in-grey-600= t('settings')
        %tbody
          = render partial: 'courier_list', collection: @couriers
      - if @pagy.pages > 1
        .text-center
          = render partial: 'pagy/nav', locals: { pagy: @pagy }

app/views/couriers/new.html.haml
%main.container
  %h1.general-title-margin
    = t('new_courier')
    .row.mb-60
      .col-sm-5
        = render partial: 'form_courier'

app/views/couriers/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin
    = t('courier')
  .row.mb-20
    .col-sm-5
      %h3.general-subtitle.mt-0= t('data')
      %p.general-address
        = t('name: ')
        %b= @courier.name
        %br
        = t('email: ')
        = @courier.email
      %hr
      %h3.general-subtitle.mt-0= t('packages')
      = t('delivered')
      = @courier.packages.where(delivery_status: true).count
      %br
      = t('undelivered')
      = @courier.packages.where(delivery_status: false).count
      %hr
      = render partial: 'form_package'

app/views/layouts/_flash_messages.html.haml
%main.container
  - flash.each do |type, message|
    - if message.is_a?(String)
      %div{class: "alert alert-#{type == 'notice' ? 'success' : 'warning'}"}
        %a{type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close"} &times;
        = message

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('home'), root_path, class: "nav-link"
      .col-sm-3
        %p.general-nav-mail support@delivery.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "https://facebook.com"}
              %i.fa.fa-facebook
          %li
            %a.nav-link{href: "https://twitter.com"}
              %i.fa.fa-twitter
          %li
            %a.nav-link{href: "https://google.com"}
              %i.fa.fa-google-plus
          %li
            %a.nav-link{href: "https://instagram.com"}
              %i.fa.fa-instagram

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", "data-toggle": "collapse", "data-target": "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t('site_name'), root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse.pl-30{"aria-expanded": "false"}
      = render 'layouts/mobile_nav'
      = render 'layouts/nav'            

app/views/layouts/_mobile_nav.html.haml
.visible-xs
  %button.close{type: "button", "aria-label": "Close"}
  %ul.nav.navbar-nav
    %li
      = link_to t('home'), root_path

app/views/layouts/_nav.html.haml
.hidden-xs
  %ul.nav.navbar-nav
    %li
      = link_to t('home'), root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Delivery
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{name: "viewport", content: "width=device-width"}
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans", rel: "stylesheet"}
    = favicon_link_tag 'favicon.png'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    = yield
    = render 'layouts/footer'

app/views/pagy/_nav.html.haml
= raw pagy_bootstrap_nav(@pagy)